### ISSUE TITLE
Share dashboards

### ISSUE THREAD

**Issue by felix-lessoer** [ironvine/elastic-m365#1]
I would like to share your dashboards in my [Kibana Dashboards gallery](https://elastic-content-share.eu/downloads/category/kibana/kibana-dashboards/) .. Would that be okay for you?

**Comment by eric-ooi** [comment]
If you want to link to the GitHub page, that's cool.  However, it looks like you actually upload dashboards and require an email address to download which we are not okay with as we want to make these freely and easily available.  We'd also like to make updates as needed and GitHub is the easiest way for us to do that.

Thanks!
