### ISSUE TITLE
Import error Kibana v7.16

### ISSUE THREAD

**Issue by darksun4life** [ironvine/elastic-m365#2]
Hello, I have the following error when trying to import the dashboards in kibana.

Sorry, there was an error

The file could not be processed due to error: "Bad Request: Unexpected end of JSON input"

**Comment by eric-ooi** [comment]
Thanks for the report.  Try the new upload and let us know if it's working now.

**Comment by darksun4life** [comment]
Hello, 
it's working now with v7.17. Thank you for your reactivity and your work!
